# Setup
title: GyuBlog
url: http://Gyuhub.github.io
paginate: 5
baseurl: ""
permalink: none

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-0124JN7YV0

# Specify the author for blog posts
author:
  name: Mingyu Park
  git: https://github.com/Gyuhub
  url: https://instagram.com/mn_g.p
  email: mngupark@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Categories
    url: /categories

  - title: Blog
    url: /archive

  - title: About
    url: /about

# Latex configuration
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax
